### ISSUE TITLE
Do we want threads to have a body?

### ISSUE THREAD

**Issue by Valkje** [gsvnet/gsvnet4#1]
In GSVnet 3, `Thread`s have a body. This body is the first 'post' of the thread. `Reply`s form the remainder of all the 'posts' on a thread. However, since every 'post' should be likable, the setup of GSVnet 3 requires a polymorphic relationship between `User`s on the one hand, and `Thread`s and `Reply`s on the other.

I do not find a body on a `Thread` very logical; there is no reason to turn the first 'post' on a thread into a `Reply` instead. This prevents the complications of a polymorphic relationship. It also prevents the updated_at timestamp of the `Thread` from being changed every time someone likes the first 'post'. (In GSVnet 3, we employ a slightly hacky solution for that problem.) Therefore, I propose to remove the body column from the `forum_threads` table and implement some logic that will create both a `Thread` and a `Reply` when someone starts a thread.

In addition, if we choose to do so, the first 'post' on a thread would not really be a reply to anything. Because of that, it might be wise to change the name of the `Reply` class to `Post`.

**Comment by haampie** [comment]
Volgens mij was het idee ooit dat je makkelijker kon zoeken naar topics (titel + eerste bericht gecombineerd), maar denk dat dat niet een belangrijke reden is.

Wat is trouwens het idee van gsvnet4? Blijft het forum ongeveer hetzelfde? Mij is verteld dat social media komen en gaan maar gsvnet blijft altijd bestaan

**Comment by Valkje** [comment]
Haha, mooi dat de grote meester na al die jaren toch nog meekijkt ;)

Het forum blijft in grote lijnen zeker hetzelfde. In die zin is de bump van 3 naar 4 niet helemaal gewaarborgd, maar tegelijkertijd zijn we ook niet bang om wel wat architecturale wijzigingen aan te brengen als we denken dat dat handig is. De voornaamste reden voor een nieuwe versie is dat de oude zo ver achterloopt dat we beter 'opnieuw' kunnen beginnen dan tien keer een update uit te voeren.

**Comment by haampie** [comment]
Haha, klinkt goed! Kan me voorstellen dat de dependencies nogal gedateerd zijn inderdaad... Zolang de website maar snappy laadt op een karige hosting provider is alles goed

**Comment by Valkje** [comment]
De bovenstaande suggesties zijn doorgevoerd. Zie 92814675a8820473b148a4037859ed7baa34beb0 t/m a806877381eb390c0040265f719d32e32a91e36a.
